import { NextResponse } from 'next/server';
import connectDB from '@/lib/db/connect';
import { Trade } from '@/lib/db/models';
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';

const generateTradeToken = (id: string) => {
  let hash = 0;
  const str = id + 'MANDI_SECRET_2026';
  for (let i = 0; i < str.length; i++) {
    hash = ((hash << 5) - hash) + str.charCodeAt(i);
    hash |= 0;
  }
  return Math.abs(hash).toString(16);
};

export async function GET(req: Request, { params }: { params: Promise<{ id: string }> }) {
  try {
    const { id } = await params;
    const url = new URL(req.url);
    const token = url.searchParams.get('token');

    // Verify token
    if (token !== generateTradeToken(id)) {
      return NextResponse.json({ error: 'Invalid or missing secure token' }, { status: 403 });
    }

    await connectDB();
    const trade = await Trade.findById(id).lean();

    if (!trade) {
      return NextResponse.json({ error: 'Trade not found' }, { status: 404 });
    }

    // Create a new PDFDocument
    const pdfDoc = await PDFDocument.create();
    
    // Embed the standard font
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    // Add a blank page
    const page = pdfDoc.addPage([595.28, 841.89]); // A4 size

    // Helper to draw text
    let currentY = 780;
    const drawText = (text: string, size: number, isBold: boolean = false, x: number = 50) => {
      page.drawText(text, {
        x,
        y: currentY,
        size,
        font: isBold ? boldFont : font,
        color: rgb(0, 0, 0),
      });
      currentY -= size + 8; // move down
    };

    drawText('Mandi Trade Audit Report', 20, true);
    currentY -= 10;
    
    // Header
    drawText(`Trade Number: ${trade.tradeNumber}`, 12);
    drawText(`Status: ${trade.status}`, 12);
    drawText(`Date: ${new Date(trade.tradeDate).toLocaleDateString()}`, 12);
    currentY -= 15;

    // Sourcing
    drawText('Sourcing Details', 16, true);
    currentY -= 5;
    trade.sourceLines?.forEach((line: any, i: number) => {
      drawText(`${i + 1}. ${line.commodityName} - ${line.quantityKg?.toString() || 0} kg from ${line.farmerName || 'Unknown'}`, 12);
      drawText(`   Purchase Cost: Rs. ${line.totalPurchaseCost?.toString() || 0}`, 12);
    });
    currentY -= 15;

    // Logistics
    drawText('Logistics & Freight', 16, true);
    currentY -= 5;
    drawText(`Vehicle Type: ${trade.logistics?.vehicleType || 'N/A'}`, 12);
    drawText(`Driver Name: ${trade.logistics?.driverName || 'N/A'}`, 12);
    drawText(`Total Freight Cost: Rs. ${trade.logistics?.freightCost?.toString() || 0}`, 12);
    currentY -= 15;

    // Financials
    drawText('Financial Summary', 16, true);
    currentY -= 5;
    drawText(`Total Source Cost: Rs. ${trade.financials?.totalSourceCost?.toString() || 0}`, 12);
    drawText(`Total Freight & Expenses: Rs. ${trade.financials?.totalFreightAndExpenses?.toString() || 0}`, 12);
    drawText(`Total Gross Sale: Rs. ${trade.financials?.totalGrossSale?.toString() || 0}`, 12);
    currentY -= 10;
    
    // Highlighted net profit
    page.drawText(`Net Profit: Rs. ${trade.financials?.netProfitAfterPeshgi?.toString() || 0}`, {
      x: 50,
      y: currentY,
      size: 14,
      font: boldFont,
      color: rgb(0.1, 0.6, 0.1), // Green
    });
    currentY -= 40;

    // Footer
    page.drawText('Generated by Mandi SaaS Platform', {
      x: 50,
      y: 50,
      size: 10,
      font,
      color: rgb(0.5, 0.5, 0.5),
    });

    // Serialize the PDF to bytes
    const pdfBytes = await pdfDoc.save();

    // In Next.js App Router, we return the raw bytes in NextResponse
    return new NextResponse(pdfBytes, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `inline; filename="Trade_${trade.tradeNumber}.pdf"`,
        'Cache-Control': 'no-store, must-revalidate',
      }
    });

  } catch (err: any) {
    console.error('PDF Generation Error:', err);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
