import { NextResponse } from 'next/server';
import connectDB from '@/lib/db/connect';
import { Trade } from '@/lib/db/models';
import PDFDocument from 'pdfkit';

// We create a simple insecure hash for the public PDF link. 
// In production, use crypto.createHmac with a real secret.
const generateTradeToken = (id: string) => {
  let hash = 0;
  const str = id + 'MANDI_SECRET_2026';
  for (let i = 0; i < str.length; i++) {
    hash = ((hash << 5) - hash) + str.charCodeAt(i);
    hash |= 0;
  }
  return Math.abs(hash).toString(16);
};

export async function GET(req: Request, { params }: { params: Promise<{ id: string }> }) {
  try {
    const { id } = await params;
    const url = new URL(req.url);
    const token = url.searchParams.get('token');

    // Verify token for public access
    if (token !== generateTradeToken(id)) {
      return NextResponse.json({ error: 'Invalid or missing secure token' }, { status: 403 });
    }

    await connectDB();
    const trade = await Trade.findById(id).lean();

    if (!trade) {
      return NextResponse.json({ error: 'Trade not found' }, { status: 404 });
    }

    // Generate PDF using PDFKit
    const doc = new PDFDocument({ margin: 50 });
    
    // We collect the PDF into a buffer
    const chunks: Buffer[] = [];
    doc.on('data', chunk => chunks.push(chunk));
    
    // Return a promise that resolves when the PDF is done
    const pdfBuffer = await new Promise<Buffer>((resolve) => {
      doc.on('end', () => resolve(Buffer.concat(chunks)));

      // Title
      doc.fontSize(20).text('Mandi Trade Audit Report', { align: 'center' });
      doc.moveDown();
      
      // Header Info
      doc.fontSize(12).text(`Trade Number: ${trade.tradeNumber}`);
      doc.text(`Status: ${trade.status}`);
      doc.text(`Date: ${new Date(trade.tradeDate).toLocaleDateString()}`);
      doc.moveDown();

      // Sourcing
      doc.fontSize(16).text('Sourcing Details', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(12);
      trade.sourceLines?.forEach((line: any, i: number) => {
        doc.text(`${i + 1}. ${line.commodityName} - ${line.quantityKg?.toString() || 0} kg from ${line.farmerName || 'Unknown Farmer'}`);
        doc.text(`   Purchase Cost: Rs. ${line.totalPurchaseCost?.toString() || 0}`);
      });
      doc.moveDown();

      // Logistics
      doc.fontSize(16).text('Logistics & Freight', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(12);
      doc.text(`Vehicle Type: ${trade.logistics?.vehicleType || 'N/A'}`);
      doc.text(`Driver Name: ${trade.logistics?.driverName || 'N/A'}`);
      doc.text(`Total Freight Cost: Rs. ${trade.logistics?.freightCost?.toString() || 0}`);
      doc.moveDown();

      // Financial Summary
      doc.fontSize(16).text('Financial Summary', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(12);
      doc.text(`Total Source Cost: Rs. ${trade.financials?.totalSourceCost?.toString() || 0}`);
      doc.text(`Total Freight & Expenses: Rs. ${trade.financials?.totalFreightAndExpenses?.toString() || 0}`);
      doc.text(`Total Gross Sale: Rs. ${trade.financials?.totalGrossSale?.toString() || 0}`);
      doc.moveDown();
      doc.fontSize(14).text(`Net Profit: Rs. ${trade.financials?.netProfitAfterPeshgi?.toString() || 0}`, { stroke: true });

      doc.moveDown(2);
      doc.fontSize(10).fillColor('gray').text('Generated by Mandi SaaS Platform', { align: 'center' });

      doc.end();
    });

    // Return the Buffer as a BodyInit
    return new NextResponse(pdfBuffer as unknown as BodyInit, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `inline; filename="Trade_${trade.tradeNumber}.pdf"`
      }
    });

  } catch (err: any) {
    console.error('PDF Generation Error:', err);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
